#!/bin/zsh
# attaches to a tmux session through mosh
declare -A dict
dict=(
  home 192.168.178.20
  alph 74.70.97.104
)

[[ $1 == '-X' ]] && x=x && shift
dest=${1:-home}
tmux_cmd="tmux a -t $dest"

if [[ $x == 'x' ]]; then
  com="autossh -X $dict[$dest] -t '$tmux_cmd'"
else
  com="mosh $dict[$dest] -- $tmux_cmd"
fi

echo "Executing $com"
eval $com
