#!/bin/zsh

if [[ $DOTFILES_HAVE_REBOUND_KEYS == 0 ]]; then
  exit 0
fi

function xm {
  xmodmap -e $1
}

function xc {
  xcape -t 200 -e $1
}

# Caps lock to left control
xm 'remove lock = Caps_Lock'
xm 'keysym Caps_Lock = Control_L'
xm 'add control = Control_L'

# Left control is also Escape
xc 'Control_L=Escape'

# Avoid Shift-0 and Shift-9
xc 'Shift_L=parenleft'
xc 'Shift_R=parenright'

# Easier return, triggered by the thumb
xc 'Alt_R=Return'

# Could try something with backspace too?


# avoid to reload this script over and over again
export DOTFILES_HAVE_REBOUND_KEYS=0
