#!/bin/zsh
# tksr - tmux kill sessions by regexp
#
# Kills all tmux sessions where greping succeeds. All arguments
# are passed to grep.
# Example: tksr -P '.*'

if [[ $@ == '' ]]; then
  echo 'Error: need a pattern to look for'
  return 1
fi

tmux ls | awk '{print $1}' | sed 's/://g' | grep $@ |\
  xargs -I{} tmux kill-session -t {}
