#!/bin/zsh
# Tries to open the github page for the current repository you are
# in, following remote origin. Uses chrome or firefox.

repo_path=$(git remote -v 2>/dev/null | grep 'origin' | tail -1 |\
  cut -d ' ' -f 1 | grep -oP '(?<=com[:/]).*/.*?(?=\.git|$)')

if [[ $repo_path == '' ]]; then
  echo "Error: No github path to go to. Are you in repository with a remote?"
  return 1
fi

gh_url=http://www.github.com/$repo_path

# Deliberately not using xdg-open, as it acts up on some of my desktops
for browser in /usr/bin/{google-chrome,firefox}; do
  if [[ -f $browser ]]; then
    echo "Visiting $gh_url"
    # supresses some firefox bugs
    $browser --new-tab $gh_url 2>/dev/null
    return 0
  fi
done

echo "Error: Neither chrome nor firefox found."
return 1
