#!/bin/zsh
# Launches a webserver on port [PORT - default 8000] to the share the current
# directory tree.

function kbj {
  echo -e '\nShutting down...'
  kill $!
}
trap 'kbj' 1 2 4

port=${1:-8000}
python -m SimpleHTTPServer $port &

pip=$(echo $(curl --silent http://ipecho.net/plain))
if [[ ! $pip == '' ]]; then
  echo "Server also accessible through $pip:$port"
  echo -n "Hit y to copy the address to the clipboard >> "
  read -t 5 var
  if [[ $var == 'y' ]]; then
    echo -n "$pip:$port" | xclip -sel clip
    echo 'Yanked!'
  else
    echo
  fi
fi

wait
