#!/bin/zsh

staged_files=$(git diff --cached --name-only --diff-filter=ACM)
top_level=$(git rev-parse --show-toplevel)

messages=()

function check_for_pattern() {
  if [[ $1 =~ $2 ]]; then
    if grep $3 "$top_level/$1" | grep -qv "#" ; then
      messages+="$3 found in $1"
    fi
  fi
}

for file in ${(f)staged_files}; do
  check_for_pattern $file 'spec.rb$' ':focus'
  check_for_pattern $file '.rb$' 'binding.pry'
  check_for_pattern $file '.spec.coffee$' 'fdescribe'
  check_for_pattern $file '.spec.coffee$' 'fit'
done

if [[ $#messages == 0 ]]; then
  exit 0
else
  echo "COMMIT ABORTED"
  for message in $messages; do
    echo $message
  done
  exit 1
fi


